### PR TITLE
upload genicam xml, fix #79

### LINKED ISSUE #79: Upload genicam xml
Create a function in CogniacNetworkCamera to upload genicam xml.

### PR DESCRIPTION
**Pull request by sergii-bond**
Here is a test case:
```
import cogniac
from cogniac.network_camera import CogniacNetworkCamera

cc = cogniac.CogniacConnection(tenant_id="your_tenant")

cam_name = "test_cam"

for c in cc.get_all_cameras():
    if c.camera_name == cam_name:
        cam = c
        print("Found a test camera")
        break
else:
    print("Creating a test camera")
    cam = CogniacNetworkCamera.create(cc, name=cam_name, url=u'gigv://169.254.23.111/')

test_xml = "test.xml"

with open(test_xml, "w") as fp:
    fp.write("some xml info")

cam.upload_genicam_xml(test_xml)
```

### CODE REVIEW

**Comment by sergii-bond** [comment]
And the test case returns `cogniac.common.ClientError: ClientError (403): {"message":"Permission Denied"}`. Is there an issue with api ?

**Review by wskish — APPROVED** [review]

**Comment by mgub** [comment]
@sergii-bond Currently that endpoint requires the "ef_device" role, which is used by EF machine users created during EF setup.

What user/tenant roles are associated with the account you're using?

**Comment by sergii-bond** [comment]
@mgub I was using a "Cogniac - Measurement" tenant_id=r2um06f1d0mr, and my local COG_USER credentials. So obviously not related to 'ef_device' role. I don't have a way to test then, could you please help to verify the code ? I also think I don't have access to s3, so won't be able to check if an xml file ends up there.

**Comment by wskish** [comment]
thinking about this some more; this code probably isn't a good fit for the sdk.  Let's move it to the edgeflow auto discovery side.

**Review by wskish — CHANGES_REQUESTED** [review]
move to autodiscovery

**Pull request closed without merging**
